### PR TITLE
Update et9x00.conf

### PR DESCRIPTION
**Pull request by kueken**
fix Frontdisplay

### CODE REVIEW

**Comment by WanWizard** [comment]
@kueken what has this for effect? Which display skin is used if 7segment is removed?

**Comment by kueken** [comment]
et9x00 has an LCD display with more than just numbers.
 The addition of 7Segment has the result that programs and media file information are no longer displayed.
All that remains is the clock and the number of the program.

**Comment by WanWizard** [comment]
Ok. 

I wondered if similar issues exist for other boxes too, someone just reported that the HD2400 display stays dark.

**Comment by WanWizard** [comment]
No mention of 7segment there, so it must be another issue. I've updated this BSP in develop.

**Comment by kueken** [comment]
I just looked in there quickly, but it's missing there
'textlcd'
https://github.com/HD-Digital/meta-gfutures/blob/fa638ecd9b8b69d823a9852034f649b75e8007c7/conf/machine/hd2400.conf#L5

**Comment by WanWizard** [comment]
Ah, that might explain it!

**Comment by kueken** [comment]
mhh...
Should I create a pull request there?
Or do you do it.
Without a textlcd, the skin display in the e2 
https://github.com/OpenPLi/enigma2/blob/develop/data/display/Makefile.am
https://github.com/OpenPLi/enigma2/blob/develop/data/display/skin_display_hd2400.xml
is not built. 
Therefore there can be no display.

**Comment by WanWizard** [comment]
It has to be a PR on meta-gfutures, as it is a BSP file that needs updating. We don't have write access to BSP's.

I'll do it later today, with a bit of luck they'll merge before Xmas.

btw: another user says that his HD2400 display works fine on 8.0-rc, so I am a bit confused now...

**Comment by kueken** [comment]
It is confusing indeed.
Is it possible that this is activated when the settings are adopted?
If the user could verify this?

From the enigma image, the assignment always runs via this feature assignment in pli.
Incidentally, the pull requests to the 'HAL' distributed there are also incorrect. Features named there do not exist in the pli image.

**Comment by WanWizard** [comment]
> Incidentally, the pull requests to the 'HAL' distributed there are also incorrect. Features named there do not exist in the pli image.

Yes, this is why I told PP we will not merge them, and Neo not to merge them either.

As we don't have (and don't want) write access to the BSP's, we can't use the same system OV and OE-A uses. I've been trying to explain this to them for a few months now...

**Pull request merged**
