### PR TITLE
Update Kernel last version 3.8.13 (Name hold 3.8.7, only fixex)

### PR DESCRIPTION
**Pull request by kueken**
Update defconfig

just a Test
please do not merge yet
We are waiting for feedback from users

### CODE REVIEW

**Comment by WanWizard** [comment]
I ran a kernel build for the ET9x00, and it compiles, so I'd say it can be merged, so it can be tested by users (I don't own an Xtrend 1st Gen box anymore).

**Comment by neo-pli-bsps** [comment]
@kueken is what @persianpros refers to a sed error, or did you forget to remove the hash? Either way, can you please correct it?

**Comment by kueken** [comment]
He just wants to point out a function in the defconfig.
But this is neither wrong nor right.
I only activated it so that the user in the pli forum might get more log files.
But his problem is obviously solved with the kernel update.
 # CONFIG_CIFS_STATS2=y
This line is meant.
It says 'y'
But it is deactivated by #.
Should be like that.
If nothing happens, everything is okay.
Cosmetic only.

**Comment by neo-pli-bsps** [comment]
if it is not active, I prefer to set it back to "is not set", it makes it clearer what is meant. I'll update it.

**Comment by kueken** [comment]
Yeah, will send the PR.
Just wanted to explain why it happened.
Was activated locally as a test in the meantime.
But really only a cosmic problem. I don't know why it's mentioned.
So what

**Comment by neo-pli-bsps** [comment]
No worries, I've already changed it.

**Comment by kueken** [comment]
ok, thx

**Pull request merged**
